Cart
Arshev/shop pull request #2
Opened 2018-07-31 08:49 UTC by Arshev

2018-07-31 18:08 UTC, index01d requested changes

2018-07-31 18:08 UTC, index01d commented on src/Cart.js
> +import {MyContext} from '../context/CartProvider';
давай все же называть CartContext

2018-07-31 18:08 UTC, index01d commented on context/CartProvider.js
> +          state: this.state,
лучше не state, а cart: this.state, потребителям незачем знать, что это state

2018-07-31 18:08 UTC, index01d commented on src/AddToCart.js
> +    render() {
в свойствах здесь можно получить продукт

2018-07-31 18:08 UTC, index01d commented on src/AddToCart.js
> +                            <button onClick={context.growCount}>Add to Cart</button>
а здесь его передать `onClick={() => context.addProduct(product)}`

2018-07-31 18:08 UTC, index01d commented on src/ProductCard.js
> +                <div><AddToCart /></div>
`<AddToCart product={product} />`

2018-08-12 14:36 UTC, Arshev commented on context/CartProvider.js
> +            items: this.state.items.push('product')
Cкажите пожалуйста, как получить тут продукт, и как правильно его добавить в state?

2018-08-15 04:32 UTC, index01d approved these changes

2018-08-15 17:52 UTC, merged